services:
  wundergraph-router:
    image: ghcr.io/wundergraph/cosmo/router:latest
    container_name: wundergraph-router
    ports:
      - '4100:4000'
    environment:
      - ROUTER_CONFIG_PATH=/app/supergraph.json
      - CONFIG_PATH=/app/config.yml
      - DEV_MODE=true
      - LISTEN_ADDR=0.0.0.0:4000
    volumes:
      - ./config/wundergraph/supergraph.json:/app/supergraph.json:ro
      - ./config/wundergraph/cosmo-config.yml:/app/config.yml:ro
    networks:
      - federation-test

  contact-server:
    image: node:20-alpine
    container_name: contact-server
    working_dir: /app
    ports:
      - '4110:4110'
    volumes:
      - .:/app
    command: npx tsx src/contact-service/contact-server.ts
    networks:
      - federation-test
    depends_on:
      - wundergraph-router

  search-server:
    image: node:20-alpine
    container_name: search-server
    working_dir: /app
    ports:
      - '4111:4111'
    volumes:
      - .:/app
    command: npx tsx src/search-service/search-server.ts
    networks:
      - federation-test
    depends_on:
      - wundergraph-router

networks:
  federation-test:
    driver: bridge
