version: 1
subgraphs:
  - name: contact
    routing_url: http://contact-server:4110/graphql
    schema:
      file: ../../src/contact-service/schema/contact.graphqls
  - name: search
    routing_url: http://search-server:4111/graphql
    schema:
      file: ../../src/search-service/schema/search.graphqls
